import { index, integer, jsonb, pgTable, text, timestamp, uniqueIndex, uuid, varchar } from 'drizzle-orm/pg-core';
import { experiments } from './experiments';

export const behaviouralInterventionDefinitions = pgTable('behavioural_intervention_definitions', {
  id: uuid('id').primaryKey().defaultRandom(), key: varchar('key', { length: 80 }).notNull(), status: varchar('status', { length: 30 }).notNull().default('DRAFT'), version: integer('version').notNull().default(1), currentVersionId: uuid('current_version_id').notNull(), createdBy: uuid('created_by').notNull(), approvedBy: uuid('approved_by'), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({ keyIdx: uniqueIndex('behavioural_intervention_definitions_key_idx').on(table.key), statusIdx: index('behavioural_intervention_definitions_status_idx').on(table.status, table.updatedAt) }));

export const behaviouralInterventionVersions = pgTable('behavioural_intervention_versions', {
  id: uuid('id').primaryKey(), definitionId: uuid('definition_id').notNull().references(() => behaviouralInterventionDefinitions.id), versionNumber: integer('version_number').notNull(), name: varchar('name', { length: 160 }).notNull(), targetBehaviour: varchar('target_behaviour', { length: 40 }).notNull(), hypothesis: text('hypothesis').notNull(), primaryMetric: varchar('primary_metric', { length: 120 }).notNull(), audience: jsonb('audience').notNull(), channel: varchar('channel', { length: 20 }).notNull(), placement: varchar('placement', { length: 40 }).notNull(), content: jsonb('content').notNull(), suppression: jsonb('suppression').notNull(), experimentId: uuid('experiment_id').notNull().references(() => experiments.id), experimentVariantKey: varchar('experiment_variant_key', { length: 40 }).notNull(), contentDigest: varchar('content_digest', { length: 64 }).notNull(), createdBy: uuid('created_by').notNull(), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({ versionIdx: uniqueIndex('behavioural_intervention_versions_definition_version_idx').on(table.definitionId, table.versionNumber), digestIdx: uniqueIndex('behavioural_intervention_versions_digest_idx').on(table.definitionId, table.contentDigest), experimentIdx: index('behavioural_intervention_versions_experiment_idx').on(table.experimentId) }));

export const behaviouralInterventionExposures = pgTable('behavioural_intervention_exposures', {
  id: uuid('id').primaryKey().defaultRandom(), definitionId: uuid('definition_id').notNull().references(() => behaviouralInterventionDefinitions.id), versionId: uuid('version_id').notNull().references(() => behaviouralInterventionVersions.id), experimentId: uuid('experiment_id').notNull().references(() => experiments.id), participantRefHash: varchar('participant_ref_hash', { length: 64 }).notNull(), deliveryKey: varchar('delivery_key', { length: 160 }).notNull(), eligibilityEvidence: jsonb('eligibility_evidence').notNull(), occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({ deliveryIdx: uniqueIndex('behavioural_intervention_exposures_delivery_idx').on(table.definitionId, table.deliveryKey), participantIdx: index('behavioural_intervention_exposures_participant_idx').on(table.definitionId, table.participantRefHash, table.occurredAt) }));

export const behaviouralInterventionOutcomes = pgTable('behavioural_intervention_outcomes', {
  id: uuid('id').primaryKey().defaultRandom(), exposureId: uuid('exposure_id').notNull().references(() => behaviouralInterventionExposures.id), definitionId: uuid('definition_id').notNull().references(() => behaviouralInterventionDefinitions.id), participantRefHash: varchar('participant_ref_hash', { length: 64 }).notNull(), outcomeKey: varchar('outcome_key', { length: 160 }).notNull(), outcome: varchar('outcome', { length: 30 }).notNull(), source: varchar('source', { length: 30 }).notNull(), evidence: jsonb('evidence').notNull(), occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({ outcomeIdx: uniqueIndex('behavioural_intervention_outcomes_key_idx').on(table.definitionId, table.outcomeKey), exposureIdx: index('behavioural_intervention_outcomes_exposure_idx').on(table.exposureId, table.occurredAt) }));

export const behaviouralInterventionEvents = pgTable('behavioural_intervention_events', {
  id: uuid('id').primaryKey().defaultRandom(), definitionId: uuid('definition_id').notNull().references(() => behaviouralInterventionDefinitions.id), action: varchar('action', { length: 40 }).notNull(), actorId: uuid('actor_id').notNull(), reason: text('reason').notNull(), evidence: jsonb('evidence').notNull(), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({ definitionIdx: index('behavioural_intervention_events_definition_idx').on(table.definitionId, table.createdAt) }));
