import { readFileSync } from 'node:fs'; import { describe, expect, it } from 'vitest'; const read = (path: string) => readFileSync(path, 'utf8');
describe('Behavioral Interventions integration guardrails', () => {
  it('registers exact RBAC and protected admin routes', () => { const permissions = read('packages/shared/src/permissions/index.ts'); for (const value of ['interventions.read','interventions.create','interventions.manage','interventions.approve','interventions.activate']) expect(permissions).toContain(value); const route = read('apps/api/src/interfaces/http/routes/admin/behavioural-interventions.ts'); expect(route).toContain("routes.use('*', authMiddleware)"); });
  it('reads consent, Customer DNA and running Experiments without mutating them', () => { const repo = read('apps/api/src/infrastructure/db/repositories/DrizzleBehaviouralInterventionRepository.ts'); for (const value of ['consentCurrentState','customerProfiles','experiments.status']) expect(repo).toContain(value); expect(repo).not.toMatch(/insert\(consent|update\(consent|delete\(consent|insert\(customerProfiles|update\(customerProfiles|insert\(experiments|update\(experiments/); });
  it('has no provider, outbox, Automation or customer communication path', () => { const source = ['apps/api/src/application/use-cases/behavioural-interventions/BehaviouralInterventionOperationsUseCase.ts','apps/api/src/infrastructure/db/repositories/DrizzleBehaviouralInterventionRepository.ts','apps/api/src/interfaces/http/routes/behavioural-interventions.ts'].map(read).join('\n'); expect(source).not.toMatch(/NotificationRouter|outbox|sendEmail|sendSms|whatsapp|automationAction|providerCalls/i); });
  it('does not accept browser-provided target achievement', () => { const route = read('apps/api/src/interfaces/http/routes/behavioural-interventions.ts'); expect(route).not.toContain('TARGET_ACHIEVED'); const useCase = read('apps/api/src/application/use-cases/behavioural-interventions/BehaviouralInterventionOperationsUseCase.ts'); expect(useCase).toContain("source: 'SERVER_MEASUREMENT'"); });
  it('does not expose consent or internal eligibility evidence to the account API', () => { const route = read('apps/api/src/interfaces/http/routes/behavioural-interventions.ts'); expect(route).not.toMatch(/eligibilityEvidence|consentRecordId|participantRefHash/); });
  it('renders truthful operating, suppression and failure states', () => { const ui = read('apps/web/src/pages/admin/behavioural-interventions/index.astro') + read('apps/web/src/pages/admin/behavioural-interventions/[id].astro'); for (const state of ['DRAFT','PENDING_APPROVAL','APPROVED','ACTIVE','PAUSED','COMPLETED','REJECTED','Permission denied','Unavailable','Empty','Stale conflict','SUPPRESSED','EXPERIMENT_NOT_RUNNING']) expect(ui).toContain(state); expect(ui).not.toMatch(/mock|sample conversion|fake metric/i); });
});
