import { beforeEach, describe, expect, it, vi } from 'vitest'; import { PERMISSIONS } from '../../packages/shared/src/permissions';
const operations = vi.hoisted(() => ({ list: vi.fn(), detail: vi.fn(), create: vi.fn(), submit: vi.fn(), approve: vi.fn(), activate: vi.fn(), pause: vi.fn(), complete: vi.fn(), eligible: vi.fn(), expose: vi.fn(), recordCustomerOutcome: vi.fn() }));
vi.mock('../../apps/api/src/infrastructure/Registry', () => ({ Registry: { getInstance: () => ({ behaviouralInterventionOperationsUseCase: operations }) } }));
vi.mock('../../apps/api/src/interfaces/http/middleware/auth', () => ({ authMiddleware: async (c: any, next: any) => { const auth = c.req.header('Authorization'); if (!auth) return c.json({ success: false }, 401); const map: Record<string,string[]> = { read: [PERMISSIONS.INTERVENTIONS_READ], create: [PERMISSIONS.INTERVENTIONS_CREATE], manage: [PERMISSIONS.INTERVENTIONS_MANAGE], approve: [PERMISSIONS.INTERVENTIONS_APPROVE], activate: [PERMISSIONS.INTERVENTIONS_ACTIVATE] }; c.set('user', { id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', permissions: map[auth.replace('Bearer ','')] ?? [] }); await next(); } }));
vi.mock('../../apps/api/src/interfaces/http/middleware/customerSession', () => ({ customerSessionMiddleware: async (c: any, next: any) => { if (c.req.header('Authorization') !== 'Bearer customer') return c.json({ success: false }, 401); c.set('userId', 'cccccccc-cccc-4ccc-8ccc-cccccccccccc'); c.set('userEmail', 'customer@proof.invalid'); await next(); }, optionalCustomerSessionMiddleware: async (c: any, next: any) => { if (c.req.header('Authorization') === 'Bearer customer') { c.set('userId', 'cccccccc-cccc-4ccc-8ccc-cccccccccccc'); c.set('userEmail', 'customer@proof.invalid'); } await next(); } }));
import app from '../../apps/api/src/interfaces/http/app'; const json = { 'Content-Type': 'application/json' }; const id = 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
const create = { key: 'guided_discovery', name: 'Guided discovery', targetBehaviour: 'PRODUCT_DISCOVERY', audience: { lifecycleStages: ['ACTIVE'] }, channel: 'ON_SITE', placement: 'ACCOUNT_GUIDANCE', content: { title: 'Explore compatible options', body: 'Review product details that match your preferences.', ctaLabel: 'Explore products', ctaPath: '/products', disclosure: 'Shown because personalization is enabled.', dismissible: true }, suppression: { maxImpressions: 2, windowHours: 168, suppressAfterDismissal: true }, experimentId: id, experimentVariantKey: 'guidance' };
describe('Behavioral Interventions protected API', () => {
  beforeEach(() => { vi.clearAllMocks(); for (const fn of Object.values(operations)) fn.mockResolvedValue([]); });
  it('requires authentication and exact read permission', async () => { expect((await app.request('/admin/behavioural-interventions')).status).toBe(401); expect((await app.request('/admin/behavioural-interventions', { headers: { Authorization: 'Bearer none' } })).status).toBe(403); expect((await app.request('/admin/behavioural-interventions', { headers: { Authorization: 'Bearer read' } })).status).toBe(200); });
  it('separates create, approval and activation privileges', async () => { expect((await app.request('/admin/behavioural-interventions', { method: 'POST', headers: { Authorization: 'Bearer read', ...json }, body: JSON.stringify(create) })).status).toBe(403); expect((await app.request('/admin/behavioural-interventions', { method: 'POST', headers: { Authorization: 'Bearer create', ...json }, body: JSON.stringify(create) })).status).toBe(201); const body = JSON.stringify({ expectedVersion: 2, reason: 'Independent ethical review', decision: 'APPROVED' }); expect((await app.request(`/admin/behavioural-interventions/${id}/approve`, { method: 'POST', headers: { Authorization: 'Bearer manage', ...json }, body })).status).toBe(403); expect((await app.request(`/admin/behavioural-interventions/${id}/approve`, { method: 'POST', headers: { Authorization: 'Bearer approve', ...json }, body })).status).toBe(200); expect((await app.request(`/admin/behavioural-interventions/${id}/activate`, { method: 'POST', headers: { Authorization: 'Bearer approve', ...json }, body })).status).toBe(403); expect((await app.request(`/admin/behavioural-interventions/${id}/activate`, { method: 'POST', headers: { Authorization: 'Bearer activate', ...json }, body })).status).toBe(200); });
  it('rejects unsupported channel and non-dismissible input before use-case execution', async () => { const response = await app.request('/admin/behavioural-interventions', { method: 'POST', headers: { Authorization: 'Bearer create', ...json }, body: JSON.stringify({ ...create, channel: 'EMAIL', content: { ...create.content, dismissible: false } }) }); expect(response.status).toBe(400); expect(operations.create).not.toHaveBeenCalled(); });
  it('protects and minimizes the account eligibility response', async () => { operations.eligible.mockResolvedValue([{ definition: { id }, version: { id: 'dddddddd-dddd-4ddd-8ddd-dddddddddddd', name: 'Guidance', targetBehaviour: 'PRODUCT_DISCOVERY', placement: 'ACCOUNT_GUIDANCE', content: create.content, hypothesis: 'internal', primaryMetric: 'internal' }, eligibilityEvidence: { consentRecordId: 'private' } }]); expect((await app.request('/account/behavioural-interventions')).status).toBe(401); const response = await app.request('/account/behavioural-interventions', { headers: { Authorization: 'Bearer customer' } }); expect(response.status).toBe(200); expect(await response.text()).not.toMatch(/consentRecordId|hypothesis|primaryMetric|private/); });
  it('never accepts browser-provided target achievement', async () => { const response = await app.request(`/account/behavioural-interventions/exposures/${id}/outcomes`, { method: 'POST', headers: { Authorization: 'Bearer customer', ...json }, body: JSON.stringify({ outcomeKey: 'target:browser', outcome: 'TARGET_ACHIEVED' }) }); expect(response.status).toBe(400); expect(operations.recordCustomerOutcome).not.toHaveBeenCalled(); });
});
