import { describe, expect, it } from 'vitest';
import { canTransitionIntervention, interventionDigest, interventionParticipantHash, validateEthicalIntervention } from '../../apps/api/src/domain/behavioural-interventions/BehaviouralIntervention';
const valid = { targetBehaviour: 'PRODUCT_DISCOVERY' as const, channel: 'ON_SITE', placement: 'ACCOUNT_GUIDANCE', audience: { lifecycleStages: ['ACTIVE'] }, content: { title: 'Explore compatible options', body: 'Review product details that match your current preferences.', ctaLabel: 'Explore products', ctaPath: '/products', disclosure: 'Shown because you enabled personalization.', dismissible: true as const }, suppression: { maxImpressions: 2, windowHours: 168, suppressAfterDismissal: true } };
describe('Behavioral Intervention ethical policy', () => {
  it('accepts truthful dismissible on-site guidance', () => expect(validateEthicalIntervention(valid)).toEqual([]));
  it.each(['Only 2 left — act now','Hurry, everyone is buying','Guaranteed result','Last chance'])('rejects manipulative copy: %s', (body) => expect(validateEthicalIntervention({ ...valid, content: { ...valid.content, body } })).not.toEqual([]));
  it('rejects providers, non-dismissible content and transaction paths', () => { expect(validateEthicalIntervention({ ...valid, channel: 'EMAIL' })).not.toEqual([]); expect(validateEthicalIntervention({ ...valid, content: { ...valid.content, dismissible: false as true } })).not.toEqual([]); expect(validateEthicalIntervention({ ...valid, content: { ...valid.content, ctaPath: '/checkout' } })).not.toEqual([]); });
  it('uses stable opaque identities/digests and bounded transitions', () => { expect(interventionParticipantHash('user-a')).toMatch(/^[a-f0-9]{64}$/); expect(interventionParticipantHash('user-a')).not.toBe(interventionParticipantHash('user-b')); expect(interventionDigest(valid)).toBe(interventionDigest(valid)); expect(canTransitionIntervention('DRAFT','PENDING_APPROVAL')).toBe(true); expect(canTransitionIntervention('DRAFT','ACTIVE')).toBe(false); });
});
