import { describe, expect, it } from 'vitest';
import { buildDeferredCanaryStatus, DeferredEmailDiagnosticCanaryGuard, EmailProviderCooldownDecisionService, parseRateLimitResponse } from '../../apps/api/src/application/services/consent/EmailRateLimitRecovery';

const now = new Date('2026-07-15T10:00:00.000Z');
const service = new EmailProviderCooldownDecisionService();
const base = { last_attempt_status: 429, last_attempt_category: 'rate_limited', last_attempt_time: now, retry_after_seconds: null, retry_after_timestamp: null, rate_limit_reset_timestamp: null, current_time: now, attempt_budget_for_slice: 1, attempts_used: 0, provider_family: 'zeptomail', recipient_classification: 'internal' as const, broad_live_send_gate_enabled: false };

describe('Slice 09-ZI rate-limit recovery', () => {
  it('parses 429 and Retry-After seconds without exposing values', () => { const parsed = parseRateLimitResponse({ status: 429, receivedAt: now, headers: { 'retry-after': '120', 'x-request-id': 'secret-looking-id' } }); expect(parsed.provider_error_category).toBe('rate_limited'); expect(parsed.retry_after_seconds).toBe(120); expect(parsed.retry_after_timestamp).toBe('2026-07-15T10:02:00.000Z'); expect(parsed.provider_request_id_hash).toMatch(/^hash_/); expect(parsed.redacted_response_summary).not.toContain('secret'); });
  it('parses Retry-After dates and reset epochs', () => { const p = parseRateLimitResponse({ status: 429, receivedAt: now, headers: { 'retry-after': 'Wed, 15 Jul 2026 10:05:00 GMT', 'x-ratelimit-reset': '1784109900' } }); expect(p.retry_after_timestamp).toBe('2026-07-15T10:05:00.000Z'); expect(p.rate_limit_reset_present).toBe(true); });
  it('defers when Retry-After is invalid or missing', () => { for (const headers of [{}, { 'retry-after': 'soon' }]) { const p = parseRateLimitResponse({ status: 429, headers }); const d = service.decide({ ...base, retry_after_seconds: p.retry_after_seconds }); expect(d.cooldown_status).toBe('unknown'); expect(d.safe_to_attempt_now).toBe(false); } });
  it('blocks while cooldown is active and allows only after elapsed', () => { const active = service.decide({ ...base, retry_after_seconds: 60, current_time: new Date('2026-07-15T10:00:30Z') }); expect(active.cooldown_status).toBe('active'); expect(active.safe_to_attempt_now).toBe(false); const elapsed = service.decide({ ...base, retry_after_seconds: 60, current_time: new Date('2026-07-15T10:01:00Z') }); expect(elapsed.cooldown_status).toBe('elapsed'); expect(elapsed.safe_to_attempt_now).toBe(true); });
  it('requires budget, internal recipient, and disabled broad sends', () => { expect(service.decide({ ...base, attempts_used: 1 }).safe_to_attempt_now).toBe(false); expect(service.decide({ ...base, recipient_classification: 'customer' }).safe_to_attempt_now).toBe(false); expect(service.decide({ ...base, broad_live_send_gate_enabled: true }).safe_to_attempt_now).toBe(false); });
  it('exposes a safe deferred status', () => { const d = service.decide(base); const status = buildDeferredCanaryStatus('rate_limited', d); expect(status.provider).toBe('transactional_email'); expect(status.broad_sends_enabled).toBe(false); expect(status.public_saves_enabled).toBe(false); expect(status.next_eligible_at).toBeNull(); });
  it('permits at most one deferred attempt and locks down', () => { const guard = new DeferredEmailDiagnosticCanaryGuard(); const eligible = service.decide({ ...base, retry_after_seconds: 0, current_time: new Date('2026-07-15T10:01:00Z') }); expect(guard.authorize(eligible)).toEqual({ ok: true }); expect(guard.authorize(eligible)).toEqual({ ok: false, reason: 'slice_attempt_budget_exhausted' }); guard.lockDown(); expect(guard.attemptCount()).toBe(1); });
  it('never enables other channels or customer paths', () => { expect(parseRateLimitResponse({ status: 200 }).redacted_response_summary).not.toContain('recipient'); });
});
