import { describe, expect, it } from 'vitest';
import { ControlledPilotCohort, authorizePilotPreferenceSave, hashPilotIdentity } from '../../apps/api/src/application/services/consent/ConsentPilotRing';

const base = { pilot_save_enabled: true, identity_ring: 'ring_1_allowlisted_verified_pilot' as const, identity_classification: 'verified_account' as const, identity_verified: true, identity_allowlisted: true, purpose_key: 'marketing_offers_campaigns', channel_key: 'email', requested_state: 'granted' as const, correlation_id: 'corr-10-c', idempotency_key: 'idem-10-c', copy_version: 'account-consent-p0-v1', source_surface: 'account_preference_centre_pilot', audit_required: true, provider_live_sends: false, provider_transport_requested: false, email_cooldown_not_bypassed: true };

describe('Slice 10-C controlled pilot cohort', () => {
  it('enforces the default cap of three', () => { const cohort = new ControlledPilotCohort(); cohort.add('one@example.test', 'synthetic', 'synthetic_internal'); cohort.add('two@example.test', 'synthetic', 'synthetic_internal'); cohort.add('three@example.test', 'synthetic', 'synthetic_internal'); expect(() => cohort.add('four@example.test', 'synthetic', 'synthetic_internal')).toThrow('pilot_cohort_cap_reached'); expect(cohort.status().cohort_size).toBe(3); });
  it('rejects cap outside bounded range', () => { expect(() => new ControlledPilotCohort(0)).toThrow('pilot_cohort_cap_out_of_bounds'); expect(() => new ControlledPilotCohort(4)).toThrow('pilot_cohort_cap_out_of_bounds'); });
  it('deduplicates the same hashed identity', () => { const cohort = new ControlledPilotCohort(); const a = cohort.add('Pilot@example.test', 'synthetic', 'synthetic_internal'); const b = cohort.add('pilot@example.test', 'synthetic', 'synthetic_internal'); expect(a.identity_hash).toBe(b.identity_hash); expect(cohort.status().cohort_size).toBe(1); });
  it('stores hash and masked identity only', () => { const cohort = new ControlledPilotCohort(); const record = cohort.add('pilot@example.test', 'synthetic', 'synthetic_internal'); expect(record.identity_hash).toBe(hashPilotIdentity('pilot@example.test')); expect(record.masked_identity).not.toContain('pilot@example.test'); expect(record.pilot_ring_name).toBe('consent_preference_save_pilot'); });
  it('accepts only synthetic, root-only or admin provisioning', () => { const cohort = new ControlledPilotCohort(); expect(() => cohort.add('x@example.test', 'synthetic', 'synthetic_internal')).not.toThrow(); });
  it('requires active membership', () => { const cohort = new ControlledPilotCohort(); const record = cohort.add('pilot@example.test', 'synthetic', 'synthetic_internal'); expect(cohort.hasActive(record.identity_hash)).toBe(true); cohort.disable(); expect(cohort.hasActive(record.identity_hash)).toBe(false); });
  it('disables the ring fail-closed', () => { const cohort = new ControlledPilotCohort(); cohort.add('pilot@example.test', 'synthetic', 'synthetic_internal'); cohort.disable(); expect(() => cohort.add('new@example.test', 'synthetic', 'synthetic_internal')).toThrow('pilot_ring_disabled'); expect(cohort.status().pilot_ring_enabled).toBe(false); });
  it('records save, withdrawal and blocked monitoring counters', () => { const cohort = new ControlledPilotCohort(); cohort.add('pilot@example.test', 'synthetic', 'synthetic_internal'); cohort.recordSave(); cohort.recordWithdrawal(); cohort.recordBlockedPublic(); cohort.recordBlockedRing3(); const status = cohort.status(); expect(status.save_success_count).toBe(1); expect(status.withdrawal_count).toBe(1); expect(status.blocked_public_attempt_count).toBe(1); expect(status.blocked_ring3_attempt_count).toBe(1); expect(status.provider_sends_enabled).toBe(false); });
  it('reports cooldown unknown safely', () => { const cohort = new ControlledPilotCohort(); expect(cohort.status().email_cooldown_status).toBe('unknown'); });
  it('allows only an active verified cohort identity save', () => { expect(authorizePilotPreferenceSave(base)).toEqual({ ok: true }); expect(authorizePilotPreferenceSave({ ...base, identity_allowlisted: false }).ok).toBe(false); expect(authorizePilotPreferenceSave({ ...base, identity_verified: false }).ok).toBe(false); });
  it.each(['anonymous', 'checkout_contact_only', 'support_only', 'legacy_imported', 'unknown_imported'] as const)('blocks Ring 3 misuse %s', identity_classification => { expect(authorizePilotPreferenceSave({ ...base, identity_classification }).ok).toBe(false); });
  it('blocks Ring 2 public writes', () => { expect(authorizePilotPreferenceSave({ ...base, identity_ring: 'ring_2_public_read_only' }).ok).toBe(false); });
  it('rejects provider, queue, campaign and side effects', () => { expect(authorizePilotPreferenceSave({ ...base, provider_transport_requested: true }).ok).toBe(false); expect(authorizePilotPreferenceSave({ ...base, queue_send_requested: true }).ok).toBe(false); expect(authorizePilotPreferenceSave({ ...base, campaign_id: 'campaign' }).ok).toBe(false); expect(authorizePilotPreferenceSave({ ...base, newsletter_id: 'newsletter' }).ok).toBe(false); expect(authorizePilotPreferenceSave({ ...base, side_effect_requested: true }).ok).toBe(false); });
  it('requires canonical save metadata', () => { for (const field of ['correlation_id', 'idempotency_key', 'copy_version', 'source_surface'] as const) expect(authorizePilotPreferenceSave({ ...base, [field]: '' }).ok).toBe(false); });
  it('never enables provider sends', () => { expect(authorizePilotPreferenceSave({ ...base, provider_live_sends: true }).ok).toBe(false); expect(new ControlledPilotCohort().status().provider_sends_enabled).toBe(false); });
});
