import { describe, expect, it } from 'vitest';
import { authorizePilotPreferenceSave, buildPilotRingStatus, hashPilotIdentity, maskPilotIdentity, parsePilotAllowlist, provisionPilotIdentity } from '../../apps/api/src/application/services/consent/ConsentPilotRing';

const base = { pilot_save_enabled: true, identity_ring: 'ring_1_allowlisted_verified_pilot' as const, identity_classification: 'verified_account' as const, identity_verified: true, identity_allowlisted: true, purpose_key: 'marketing_offers_campaigns', channel_key: 'email', requested_state: 'granted' as const, correlation_id: 'corr-10-ab2', idempotency_key: 'idem-10-ab2', copy_version: 'account-consent-p0-v1', source_surface: 'account_preference_centre_pilot', audit_required: true, provider_live_sends: false, provider_transport_requested: false, email_cooldown_not_bypassed: true };

describe('Slice 10-AB2 secure Ring 1 provisioning and save guard', () => {
  it('accepts synthetic provisioning', () => { const r = provisionPilotIdentity('synthetic-ring1@example.test', 'synthetic'); expect(r.ring).toBe('ring_1_allowlisted_verified_pilot'); expect(r.source).toBe('synthetic_uat'); });
  it('accepts root-only and admin provisioning sources', () => { expect(provisionPilotIdentity('root@example.test', 'root_only').source).toBe('configured_hash_allowlist'); expect(provisionPilotIdentity('admin@example.test', 'admin').source).toBe('configured_hash_allowlist'); });
  it.each(['chat', 'public_form', 'checkout', 'support', 'legacy'] as const)('rejects unsafe provisioning source %s', source => { expect(() => provisionPilotIdentity('x@example.test', source)).toThrow('unsafe_pilot_provisioning_source'); });
  it('stores only hash and masked identity', () => { const r = provisionPilotIdentity('Pilot@Example.Test', 'synthetic'); expect(r.identity_hash).toBe(hashPilotIdentity('pilot@example.test')); expect(r.masked_identity).toBe('pi***@ex***'); expect(JSON.stringify(r)).not.toContain('Pilot@Example.Test'); });
  it('normalizes hashing deterministically', () => { expect(hashPilotIdentity(' PILOT@example.test ')).toBe(hashPilotIdentity('pilot@example.test')); });
  it('never returns a full identity from masking', () => { expect(maskPilotIdentity('+256700123456')).not.toContain('256700123456'); expect(maskPilotIdentity('pilot@example.test')).not.toContain('pilot@example.test'); });
  it('parses exactly hashed allowlist entries', () => { const h = hashPilotIdentity('pilot@example.test'); expect(parsePilotAllowlist(h)).toHaveLength(1); expect(parsePilotAllowlist('pilot@example.test')).toHaveLength(0); });
  it('allows a verified allowlisted Ring 1 grant', () => { expect(authorizePilotPreferenceSave(base)).toEqual({ ok: true }); });
  it('allows a Ring 1 withdrawal', () => { expect(authorizePilotPreferenceSave({ ...base, requested_state: 'withdrawn' })).toEqual({ ok: true }); });
  it('blocks Ring 2 and Ring 3', () => { expect(authorizePilotPreferenceSave({ ...base, identity_ring: 'ring_2_public_read_only' }).ok).toBe(false); expect(authorizePilotPreferenceSave({ ...base, identity_ring: 'ring_3_blocked_external' }).ok).toBe(false); });
  it('requires verified and allowlisted Ring 1 identity', () => { expect(authorizePilotPreferenceSave({ ...base, identity_verified: false }).ok).toBe(false); expect(authorizePilotPreferenceSave({ ...base, identity_allowlisted: false }).ok).toBe(false); });
  it.each(['anonymous', 'checkout_contact_only', 'support_only', 'legacy_imported', 'unknown_imported'] as const)('rejects identity classification %s', identity_classification => { expect(authorizePilotPreferenceSave({ ...base, identity_classification }).ok).toBe(false); });
  it('requires correlation, idempotency, copy and source', () => { for (const field of ['correlation_id', 'idempotency_key', 'copy_version', 'source_surface'] as const) expect(authorizePilotPreferenceSave({ ...base, [field]: '' }).ok).toBe(false); });
  it('requires audit and explicit purpose/channel', () => { expect(authorizePilotPreferenceSave({ ...base, audit_required: false }).ok).toBe(false); expect(authorizePilotPreferenceSave({ ...base, purpose_key: '' }).ok).toBe(false); expect(authorizePilotPreferenceSave({ ...base, channel_key: '' }).ok).toBe(false); });
  it('rejects provider, queue, campaign and side-effect requests', () => { expect(authorizePilotPreferenceSave({ ...base, provider_transport_requested: true }).ok).toBe(false); expect(authorizePilotPreferenceSave({ ...base, queue_send_requested: true }).ok).toBe(false); expect(authorizePilotPreferenceSave({ ...base, campaign_id: 'x' }).ok).toBe(false); expect(authorizePilotPreferenceSave({ ...base, newsletter_id: 'x' }).ok).toBe(false); expect(authorizePilotPreferenceSave({ ...base, side_effect_requested: true }).ok).toBe(false); });
  it('requires pilot save gate and disabled live sends', () => { expect(authorizePilotPreferenceSave({ ...base, pilot_save_enabled: false }).ok).toBe(false); expect(authorizePilotPreferenceSave({ ...base, provider_live_sends: true }).ok).toBe(false); });
  it('returns truthful Ring 1/Ring 2 status', () => { const s = buildPilotRingStatus({ save_enabled: true, allowlist_count: 1, cooldown_safe_to_attempt: false }); expect(s.ring_1).toBe('allowlisted_verified_pilot'); expect(s.ring_2).toBe('public_read_only'); expect(s.provider_sends_enabled).toBe(false); });
  it('reports no identity without exposing raw values', () => { const s = buildPilotRingStatus({ save_enabled: false, allowlist_count: 0, cooldown_safe_to_attempt: false }); expect(s.ring_1).toBe('ready_save_blocked_no_safe_identity'); expect(JSON.stringify(s)).not.toContain('@'); });
});
