import { readFileSync } from 'node:fs'; import { describe, expect, it } from 'vitest';
const read = (path: string) => readFileSync(path, 'utf8');
describe('Survey integration guardrails', () => {
  it('registers exact RBAC and protected routes', () => { const permissions = read('packages/shared/src/permissions/index.ts'); for (const value of ['surveys.read','surveys.create','surveys.manage','surveys.approve','surveys.activate','surveys.export']) expect(permissions).toContain(value); const routes = read('apps/api/src/interfaces/http/routes/admin/surveys.ts'); expect(routes).toContain("routes.use('*', authMiddleware)"); expect(routes).toContain('PERMISSIONS.SURVEYS_EXPORT'); });
  it('reads consent and Customer DNA without a consent mutation path', () => { const repo = read('apps/api/src/infrastructure/db/repositories/DrizzleSurveyRepository.ts'); expect(repo).toContain('consentCurrentState'); expect(repo).toContain('customerProfiles'); expect(repo).not.toMatch(/insert\(consent|update\(consent|delete\(consent/); });
  it('has no provider, outbox, invitation, or customer communication integration', () => { const files = ['apps/api/src/application/use-cases/surveys/SurveyOperationsUseCase.ts','apps/api/src/infrastructure/db/repositories/DrizzleSurveyRepository.ts','apps/api/src/interfaces/http/routes/surveys.ts'].map(read).join('\n'); expect(files).not.toMatch(/NotificationRouter|provider|outbox|sendEmail|sendSms|whatsapp|invitation/i); });
  it('exposes persisted admin states and no static sample metrics', () => { const ui = read('apps/web/src/pages/admin/surveys/index.astro') + read('apps/web/src/pages/admin/surveys/[id].astro'); for (const state of ['DRAFT','PENDING_APPROVAL','APPROVED','ACTIVE','PAUSED','CLOSED','REJECTED','Permission denied','Unavailable','Empty','Stale conflict']) expect(ui).toContain(state); expect(ui).not.toMatch(/mock|sample metrics/i); });
  it('provides a real consent-filtered customer response surface', () => { const ui = read('apps/web/src/pages/account/surveys.astro'); expect(ui).toContain('/account/surveys'); expect(ui).toContain('/complete'); expect(ui).toContain('without contact details'); });
});
