import { beforeEach, describe, expect, it, vi } from 'vitest';
import { PERMISSIONS } from '../../packages/shared/src/permissions';
const operations = vi.hoisted(() => ({ list: vi.fn(), detail: vi.fn(), create: vi.fn(), submit: vi.fn(), approve: vi.fn(), activate: vi.fn(), pause: vi.fn(), close: vi.fn(), analysis: vi.fn(), export: vi.fn() }));
vi.mock('../../apps/api/src/infrastructure/Registry', () => ({ Registry: { getInstance: () => ({ surveyOperationsUseCase: operations }) } }));
vi.mock('../../apps/api/src/interfaces/http/middleware/auth', () => ({ authMiddleware: async (c: any, next: any) => { const auth = c.req.header('Authorization'); if (!auth) return c.json({ success: false }, 401); const map: Record<string, string[]> = { read: [PERMISSIONS.SURVEYS_READ], create: [PERMISSIONS.SURVEYS_CREATE], manage: [PERMISSIONS.SURVEYS_MANAGE], approve: [PERMISSIONS.SURVEYS_APPROVE], activate: [PERMISSIONS.SURVEYS_ACTIVATE], export: [PERMISSIONS.SURVEYS_EXPORT], all: Object.values(PERMISSIONS) }; c.set('user', { id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', permissions: map[auth.replace('Bearer ', '')] ?? [] }); await next(); } }));
import app from '../../apps/api/src/interfaces/http/app';
const json = { 'Content-Type': 'application/json' }; const id = 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
describe('Survey protected operating surface', () => {
  beforeEach(() => { vi.clearAllMocks(); for (const fn of Object.values(operations)) fn.mockResolvedValue([]); });
  it('requires authentication and exact read permission', async () => { expect((await app.request('/admin/surveys')).status).toBe(401); expect((await app.request('/admin/surveys', { headers: { Authorization: 'Bearer forbidden' } })).status).toBe(403); expect((await app.request('/admin/surveys', { headers: { Authorization: 'Bearer read' } })).status).toBe(200); });
  it('keeps creation separately privileged and validates immutable questions', async () => { const body = JSON.stringify({ key: 'fit_check', title: 'Fit check', description: '', purposeKey: 'personalization', questions: [{ key: 'fit', prompt: 'How well did this fit?', type: 'SCALE', required: true, min: 0, max: 10 }], audience: { lifecycleStages: [] } }); expect((await app.request('/admin/surveys', { method: 'POST', headers: { Authorization: 'Bearer read', ...json }, body })).status).toBe(403); expect((await app.request('/admin/surveys', { method: 'POST', headers: { Authorization: 'Bearer create', ...json }, body })).status).toBe(201); });
  it('separates approval, activation and export privileges', async () => { const approval = JSON.stringify({ expectedVersion: 2, reason: 'Independent review', decision: 'APPROVED' }); const operation = JSON.stringify({ expectedVersion: 3, reason: 'Approved in-app launch' }); expect((await app.request(`/admin/surveys/${id}/approve`, { method: 'POST', headers: { Authorization: 'Bearer manage', ...json }, body: approval })).status).toBe(403); expect((await app.request(`/admin/surveys/${id}/approve`, { method: 'POST', headers: { Authorization: 'Bearer approve', ...json }, body: approval })).status).toBe(200); expect((await app.request(`/admin/surveys/${id}/activate`, { method: 'POST', headers: { Authorization: 'Bearer approve', ...json }, body: operation })).status).toBe(403); expect((await app.request(`/admin/surveys/${id}/activate`, { method: 'POST', headers: { Authorization: 'Bearer activate', ...json }, body: operation })).status).toBe(200); expect((await app.request(`/admin/surveys/${id}/export`, { headers: { Authorization: 'Bearer read' } })).status).toBe(403); expect((await app.request(`/admin/surveys/${id}/export`, { headers: { Authorization: 'Bearer export' } })).status).toBe(200); });
});
