import productImages from '../generated/product-images.json';
import staticImages from '../generated/static-images.json';

/**
 * Responsive candidates for a product image (2026-09-13). Two sources:
 *  - media-library renditions under /uploads/assets/<id>/: every asset that has
 *    a pdp.webp (1024) also has card.webp (480) and thumb.webp (160) — the
 *    generator writes all purposes at upload (checked in production: 26 of 26);
 *  - the legacy /products/*.webp catalogue files, whose 320/640 variants are
 *    generated into /public and listed in the committed manifest.
 * Anything else returns null and the <img> keeps its single src.
 */
type Manifest = Record<string, { width: number; height: number; variants: { w: number; url: string }[] }>;
const MANIFEST = productImages as Manifest;

type StaticEntry = { source: string; variants: { w: number; url: string }[] };
const AVIF_BY_SOURCE = new Map<string, string>(
  Object.values(staticImages as Record<string, StaticEntry>)
    .filter((e) => e.variants.length > 0 && e.variants.every((v) => v.url.endsWith('.avif')))
    .map((e) => [e.source, e.variants.map((v) => `${v.url} ${v.w}w`).join(', ')]),
);

/**
 * AVIF srcset generated by scripts/images/optimise-static-images.mjs for a
 * static source image (e.g. '/hero/range.jpg'), or null. Offered ahead of
 * WebP in a <picture>; browsers without AVIF keep using the WebP source.
 */
export function staticAvifSrcset(sourceUrl: string | null | undefined): string | null {
  return sourceUrl ? AVIF_BY_SOURCE.get(sourceUrl) ?? null : null;
}

/**
 * Card grids are two columns up to 1023px (the owner's phone layout, kept on
 * tablets) and 3–4 columns of about 300px above. "33vw" from 641px told a
 * tablet each card was a third of the screen while it was half, so the browser
 * picked a rendition too small and the photo was upscaled. Shorter than before:
 * this string repeats on every card of the home document.
 */
export const CARD_SIZES = '(max-width: 1023px) 50vw, 320px';
export const STAGE_SIZES = '(max-width: 640px) 160px, 320px';
/**
 * Focus 4 — the product page's main stage: near-full width on phones, then a
 * column of the two-column layout (56% of a ≤1280px container), capped so a
 * 1920px screen does not request a 2048 master. Matches the CSS in ProductGallery.
 */
export const PDP_STAGE_SIZES = '(max-width: 1023px) calc(100vw - 32px), (max-width: 1280px) 56vw, 700px';
/** Focus 4 — preview row: 56–88px squares, so the 160px thumb rendition is always the right candidate. */
export const PDP_THUMB_SIZES = '88px';

/**
 * Focus 4 — the small rendition beside a media-library rendition URL, or null
 * when the URL is not a library rendition (legacy /products/*.webp keep one src).
 * The generator writes thumb/card/pdp together for any source ≥ 480px; a
 * smaller source has no thumb and the caller falls back to the display URL.
 */
export function productThumbUrl(url: string | null | undefined): string | null {
  if (!url) return null;
  const m = url.match(/^(\/uploads\/assets\/[^?#]+\/)pdp\.webp$/);
  return m ? `${m[1]}thumb.webp` : null;
}

export function productSrcset(url: string | null | undefined): string | null {
  if (!url) return null;
  const m = url.match(/^(\/uploads\/assets\/[^?#]+\/)pdp\.webp$/);
  if (m) return `${m[1]}thumb.webp 160w, ${m[1]}card.webp 480w, ${url} 1024w`;
  const entry = MANIFEST[url];
  if (entry && entry.variants.length > 1) return entry.variants.map((v) => `${v.url} ${v.w}w`).join(', ');
  return null;
}
