import '../config/env';
import { randomUUID } from 'node:crypto';
import { eq, inArray, sql } from 'drizzle-orm';
import { BehaviouralInterventionError, BehaviouralInterventionOperationsUseCase } from '../application/use-cases/behavioural-interventions/BehaviouralInterventionOperationsUseCase';
import { interventionParticipantHash } from '../domain/behavioural-interventions/BehaviouralIntervention';
import { deterministicVariant } from '../domain/experiments/Experiment';
import { db, endDbConnection } from '../infrastructure/db/client';
import { DrizzleBehaviouralInterventionRepository } from '../infrastructure/db/repositories/DrizzleBehaviouralInterventionRepository';
import { behaviouralInterventionDefinitions, behaviouralInterventionEvents, behaviouralInterventionExposures, behaviouralInterventionOutcomes, behaviouralInterventionVersions } from '../infrastructure/db/schema/behavioural_interventions';
import { consentCurrentState } from '../infrastructure/db/schema/consent';
import { customerProfiles } from '../infrastructure/db/schema/customer_dna';
import { experimentAssignments, experimentExposures, experiments, experimentVariants } from '../infrastructure/db/schema/experiments';
import { users } from '../infrastructure/db/schema/identity';

const assert: (value: unknown, message: string) => asserts value = (value, message) => { if (!value) throw new Error(message); };
async function protectedCounts() { const result: any = await db.execute(sql`select (select count(*)::int from consent_events) consent_events,(select count(*)::int from consent_records) consent_records,(select count(*)::int from customer_preferences) preferences,(select count(*)::int from outbox_events) outbox,(select count(*)::int from notification_attempts) notifications,(select count(*)::int from orders) orders,(select count(*)::int from payment_attempts) payments`); return (result.rows ?? result)[0] as Record<string, number>; }
async function main() {
  if (process.env.NODE_ENV === 'production') throw new Error('REFUSING_TO_RUN_IN_PRODUCTION');
  const creator = randomUUID(), approver = randomUUID(), operator = randomUUID(), eligibleUser = randomUUID(), noConsentUser = randomUUID(), experimentId = randomUUID(); const variants = [{ key: 'control', name: 'Control', weightBasisPoints: 5000 },{ key: 'guidance', name: 'Guidance', weightBasisPoints: 5000 }]; const treatmentVariantKey = deterministicVariant(experimentId, interventionParticipantHash(eligibleUser), variants).key; let freshEligibleUser = randomUUID(); while (deterministicVariant(experimentId, interventionParticipantHash(freshEligibleUser), variants).key !== treatmentVariantKey) freshEligibleUser = randomUUID(); let controlUser = randomUUID(); while (deterministicVariant(experimentId, interventionParticipantHash(controlUser), variants).key === treatmentVariantKey) controlUser = randomUUID(); let definitionId: string | null = null; let report: Record<string, unknown> = {}; let failure: unknown; const providerCalls = 0;
  try {
    const before = await protectedCounts();
    await db.insert(users).values([{ id: eligibleUser, email: `intervention-${eligibleUser}@proof.invalid`, passwordHash: 'proof' },{ id: freshEligibleUser, email: `intervention-${freshEligibleUser}@proof.invalid`, passwordHash: 'proof' },{ id: controlUser, email: `intervention-${controlUser}@proof.invalid`, passwordHash: 'proof' },{ id: noConsentUser, email: `intervention-${noConsentUser}@proof.invalid`, passwordHash: 'proof' }]);
    await db.insert(customerProfiles).values([{ accountUserId: eligibleUser, primaryLifecycleStage: 'ACTIVE', identityConfidence: 'HIGH', consentEligible: true },{ accountUserId: freshEligibleUser, primaryLifecycleStage: 'ACTIVE', identityConfidence: 'HIGH', consentEligible: true },{ accountUserId: controlUser, primaryLifecycleStage: 'ACTIVE', identityConfidence: 'HIGH', consentEligible: true },{ accountUserId: noConsentUser, primaryLifecycleStage: 'ACTIVE', identityConfidence: 'HIGH', consentEligible: true }]);
    await db.insert(consentCurrentState).values([{ userId: eligibleUser, personalizationGranted: true, lastGrantType: 'explicit', lastNoticeVersion: 'proof' },{ userId: freshEligibleUser, personalizationGranted: true, lastGrantType: 'explicit', lastNoticeVersion: 'proof' },{ userId: controlUser, personalizationGranted: true, lastGrantType: 'explicit', lastNoticeVersion: 'proof' },{ userId: noConsentUser, personalizationGranted: false, lastGrantType: 'explicit', lastNoticeVersion: 'proof' }]);
    await db.insert(experiments).values({ id: experimentId, key: `intervention_${experimentId.replaceAll('-','').slice(0,12)}`, name: 'Behavioral intervention proof', hypothesis: 'Truthful compatibility guidance increases informed product discovery.', primaryMetric: 'qualified_product_detail_views', status: 'READY', createdBy: creator }); await db.insert(experimentVariants).values(variants.map((variant) => ({ experimentId, ...variant })));
    const operations = new BehaviouralInterventionOperationsUseCase(new DrizzleBehaviouralInterventionRepository()); const common = { key: `guidance_${randomUUID().replaceAll('-','').slice(0,12)}`, name: 'Compatible product guidance', targetBehaviour: 'PRODUCT_DISCOVERY' as const, audience: { lifecycleStages: ['ACTIVE'] }, channel: 'ON_SITE' as const, placement: 'ACCOUNT_GUIDANCE', content: { title: 'Explore compatible options', body: 'Review product details that match your current preferences.', ctaLabel: 'Explore products', ctaPath: '/products', disclosure: 'Shown because you enabled personalization.', dismissible: true as const }, suppression: { maxImpressions: 1, windowHours: 168, suppressAfterDismissal: true }, experimentId, experimentVariantKey: treatmentVariantKey, actorId: creator };
    let darkPatternDenied = false; try { await operations.create({ ...common, key: `${common.key}_bad`, content: { ...common.content, body: 'Only 2 left — act now!' } }); } catch (error) { darkPatternDenied = error instanceof BehaviouralInterventionError && error.code === 'UNETHICAL_OR_INVALID_INTERVENTION'; } assert(darkPatternDenied, 'Manipulative copy was accepted.');
    const created = await operations.create(common); definitionId = created.id; const submitted = await operations.submit({ id: created.id, expectedVersion: created.version, actorId: creator, reason: 'Ready for independent ethical review' });
    let selfApprovalDenied = false; try { await operations.approve({ id: created.id, expectedVersion: submitted.version, actorId: creator, reason: 'Self approval', decision: 'APPROVED' }); } catch (error) { selfApprovalDenied = error instanceof BehaviouralInterventionError && error.code === 'STALE_OR_INELIGIBLE'; } assert(selfApprovalDenied, 'Creator approved own intervention.');
    const approved = await operations.approve({ id: created.id, expectedVersion: submitted.version, actorId: approver, reason: 'Ethics, audience and suppression reviewed', decision: 'APPROVED' }); let experimentGateDenied = false; try { await operations.activate({ id: created.id, expectedVersion: approved.version, actorId: operator, reason: 'Attempt before experiment runs' }); } catch (error) { experimentGateDenied = error instanceof BehaviouralInterventionError && error.code === 'STALE_OR_INELIGIBLE'; } assert(experimentGateDenied, 'Intervention activated before experiment was running.');
    await db.update(experiments).set({ status: 'RUNNING' }).where(eq(experiments.id, experimentId)); const active = await operations.activate({ id: created.id, expectedVersion: approved.version, actorId: operator, reason: 'Experiment is running and gates passed' });
    assert((await operations.eligible(eligibleUser)).length === 1 && (await operations.eligible(freshEligibleUser)).length === 1, 'Eligible treatment customer was excluded.'); assert((await operations.eligible(controlUser)).length === 0, 'Control-variant customer received the intervention.'); assert((await operations.eligible(noConsentUser)).length === 0, 'Customer without personalization consent was included.'); await db.update(consentCurrentState).set({ personalizationGranted: false }).where(eq(consentCurrentState.userId, freshEligibleUser)); let consentRecheckDenied = false; try { await operations.expose({ definitionId: active.id, userId: freshEligibleUser, deliveryKey: `revoked:${randomUUID()}` }); } catch (error) { consentRecheckDenied = error instanceof BehaviouralInterventionError && error.code === 'SUPPRESSED'; } assert(consentRecheckDenied, 'Exposure did not recheck current consent.'); await db.update(consentCurrentState).set({ personalizationGranted: true }).where(eq(consentCurrentState.userId, freshEligibleUser));
    const deliveries = [`delivery:${randomUUID()}`,`delivery:${randomUUID()}`]; const exposures = await Promise.allSettled(deliveries.map((deliveryKey) => operations.expose({ definitionId: active.id, userId: eligibleUser, deliveryKey }))); const exposureWinners = exposures.filter((item) => item.status === 'fulfilled').length; assert(exposureWinners === 1, 'Concurrent frequency cap did not produce one exposure winner.'); const winner = exposures.find((item): item is PromiseFulfilledResult<Awaited<ReturnType<typeof operations.expose>>> => item.status === 'fulfilled')!.value; const duplicateExposure = await operations.expose({ definitionId: active.id, userId: eligibleUser, deliveryKey: winner.exposure.deliveryKey }); assert(duplicateExposure.duplicate, 'Exposure retry was not idempotent.');
    let ownershipDenied = false; try { await operations.recordCustomerOutcome({ exposureId: winner.exposure.id, userId: noConsentUser, outcomeKey: `engaged:${randomUUID()}`, outcome: 'ENGAGED' }); } catch (error) { ownershipDenied = error instanceof BehaviouralInterventionError && error.code === 'EXPOSURE_NOT_FOUND'; } assert(ownershipDenied, 'Exposure ownership was not enforced.');
    const engageKey = `engaged:${randomUUID()}`; await operations.recordCustomerOutcome({ exposureId: winner.exposure.id, userId: eligibleUser, outcomeKey: engageKey, outcome: 'ENGAGED' }); const duplicateOutcome = await operations.recordCustomerOutcome({ exposureId: winner.exposure.id, userId: eligibleUser, outcomeKey: engageKey, outcome: 'ENGAGED' }); assert(duplicateOutcome.duplicate, 'Outcome retry was not idempotent.'); await operations.recordMeasuredTarget({ exposureId: winner.exposure.id, measurementEventId: `metric:${randomUUID()}` }); await operations.recordCustomerOutcome({ exposureId: winner.exposure.id, userId: eligibleUser, outcomeKey: `dismissed:${randomUUID()}`, outcome: 'DISMISSED' }); assert((await operations.eligible(eligibleUser)).length === 0, 'Dismissed customer was not suppressed.');
    const detail = await operations.detail(active.id); assert(detail.measurement.exposures === 1 && detail.measurement.engaged === 1 && detail.measurement.dismissed === 1 && detail.measurement.targetAchieved === 1, 'Persisted measurement aggregates are not truthful.'); const [experimentCounts] = await db.select({ assignments: sql<number>`count(distinct ${experimentAssignments.id})::int`, exposures: sql<number>`count(distinct ${experimentExposures.id})::int` }).from(experimentAssignments).leftJoin(experimentExposures, eq(experimentExposures.assignmentId, experimentAssignments.id)).where(eq(experimentAssignments.experimentId, experimentId)); assert(experimentCounts.assignments === 1 && experimentCounts.exposures === 1, 'Experiment assignment/exposure diverged from the intervention exposure.'); const paused = await operations.pause({ id: active.id, expectedVersion: active.version, actorId: operator, reason: 'Proof pause' }); assert((await operations.eligible(freshEligibleUser)).length === 0, 'Paused intervention remained eligible.'); const finalDetail = await operations.detail(active.id);
    const types: any = await db.execute(sql`select jsonb_typeof(audience) audience_type,jsonb_typeof(content) content_type,jsonb_typeof(suppression) suppression_type from behavioural_intervention_versions where definition_id=${active.id}`); const native = (types.rows ?? types)[0]; const after = await protectedCounts(); for (const key of Object.keys(before)) assert(before[key] === after[key], `${key} changed during intervention proof.`);
    report = { lifecycle: 'DRAFT->PENDING_APPROVAL->APPROVED->ACTIVE->PAUSED', darkPatternDenied, selfApprovalDenied, experimentGateDenied, consentGateDenied: true, consentRecheckDenied, audienceEligible: true, controlVariantSuppressed: true, treatmentVariantKey, exposureWinners, experimentAssignments: experimentCounts.assignments, experimentExposures: experimentCounts.exposures, duplicateExposure: duplicateExposure.duplicate, ownershipDenied, duplicateOutcome: duplicateOutcome.duplicate, dismissedSuppressed: true, pauseSuppressed: paused.status === 'PAUSED', measuredExposures: detail.measurement.exposures, engaged: detail.measurement.engaged, dismissed: detail.measurement.dismissed, targetAchieved: detail.measurement.targetAchieved, nativeAudienceJsonb: native.audience_type === 'object', nativeContentJsonb: native.content_type === 'object', nativeSuppressionJsonb: native.suppression_type === 'object', governanceEvents: finalDetail.events.length, consentWrites: 0, preferenceWrites: 0, outboxDelta: 0, notificationDelta: 0, orderDelta: 0, paymentDelta: 0, providerCalls };
  } catch (error) { failure = error; }
  finally { try { if (definitionId) { await db.delete(behaviouralInterventionOutcomes).where(eq(behaviouralInterventionOutcomes.definitionId, definitionId)); await db.delete(behaviouralInterventionExposures).where(eq(behaviouralInterventionExposures.definitionId, definitionId)); await db.delete(behaviouralInterventionEvents).where(eq(behaviouralInterventionEvents.definitionId, definitionId)); await db.delete(behaviouralInterventionVersions).where(eq(behaviouralInterventionVersions.definitionId, definitionId)); await db.delete(behaviouralInterventionDefinitions).where(eq(behaviouralInterventionDefinitions.id, definitionId)); } await db.delete(experimentExposures).where(eq(experimentExposures.experimentId, experimentId)); await db.delete(experimentAssignments).where(eq(experimentAssignments.experimentId, experimentId)); await db.delete(experimentVariants).where(eq(experimentVariants.experimentId, experimentId)); await db.delete(experiments).where(eq(experiments.id, experimentId)); const userIds = [eligibleUser,freshEligibleUser,controlUser,noConsentUser]; await db.delete(consentCurrentState).where(inArray(consentCurrentState.userId, userIds)); await db.delete(customerProfiles).where(inArray(customerProfiles.accountUserId, userIds)); await db.delete(users).where(inArray(users.id, userIds)); const residue: any = await db.execute(sql`select (select count(*)::int from behavioural_intervention_definitions where id=${definitionId})+(select count(*)::int from experiments where id=${experimentId})+(select count(*)::int from users where id in (${eligibleUser},${freshEligibleUser},${controlUser},${noConsentUser})) count`); report.proofResidue = Number((residue.rows ?? residue)[0].count); if (report.proofResidue !== 0) failure ??= new Error('BEHAVIOURAL_INTERVENTION_PROOF_RESIDUE'); } catch (error) { failure ??= error; } try { await endDbConnection(); } catch (error) { failure ??= error; } }
  console.log(JSON.stringify({ ...report, verdict: failure ? 'FAIL' : 'PASS' })); if (failure) throw failure;
}
main().catch((error) => { console.error('BEHAVIOURAL_INTERVENTIONS_PROOF_ERROR', error instanceof Error ? error.message : String(error)); process.exitCode = 1; });
