import { Hono } from 'hono';
import { z } from 'zod';
import { PERMISSIONS } from '@goldplus/shared';
import { Registry } from '../../../../infrastructure/Registry';
import { BehaviouralInterventionError } from '../../../../application/use-cases/behavioural-interventions/BehaviouralInterventionOperationsUseCase';
import { authMiddleware } from '../../middleware/auth';
import { requirePermissions } from '../../middleware/permissions';

// audit-exempt: intervention governance mutations append immutable behavioural_intervention_events transactionally.
const routes = new Hono(); routes.use('*', authMiddleware); const actor = (c: any) => (c.get('user') as { id: string }).id;
const createBody = z.object({ key: z.string(), name: z.string(), targetBehaviour: z.enum(['PRODUCT_DISCOVERY','CHECKOUT_COMPLETION','PRODUCT_EDUCATION','FEEDBACK_COMPLETION']), audience: z.object({ lifecycleStages: z.array(z.string()).max(10) }), channel: z.literal('ON_SITE'), placement: z.string(), content: z.object({ title: z.string(), body: z.string(), ctaLabel: z.string(), ctaPath: z.string(), disclosure: z.string(), dismissible: z.literal(true) }), suppression: z.object({ maxImpressions: z.number().int(), windowHours: z.number().int(), suppressAfterDismissal: z.boolean() }), experimentId: z.string().uuid(), experimentVariantKey: z.string() });
const operationBody = z.object({ expectedVersion: z.number().int().positive(), reason: z.string().trim().min(3).max(1000), decision: z.enum(['APPROVED','REJECTED']).optional() });
const fail = (c: any, error: unknown) => { const code = error instanceof BehaviouralInterventionError ? error.code : 'INTERVENTION_OPERATION_FAILED'; const status = code === 'INTERVENTION_NOT_FOUND' ? 404 : code === 'STALE_OR_INELIGIBLE' ? 409 : 400; return c.json({ success: false, error: { code, message: error instanceof Error ? error.message : 'Intervention operation failed.' } }, status); };
routes.get('/', requirePermissions([PERMISSIONS.INTERVENTIONS_READ], 'PERMISSION_DENIED'), async (c) => c.json({ success: true, data: await Registry.getInstance().behaviouralInterventionOperationsUseCase.list() }));
routes.post('/', requirePermissions([PERMISSIONS.INTERVENTIONS_CREATE], 'PERMISSION_DENIED'), async (c) => { const body = createBody.safeParse(await c.req.json().catch(() => null)); if (!body.success) return c.json({ success: false, error: { code: 'INVALID_BODY', message: body.error.issues[0]?.message ?? 'Invalid body.' } }, 400); try { return c.json({ success: true, data: await Registry.getInstance().behaviouralInterventionOperationsUseCase.create({ ...body.data, actorId: actor(c) }) }, 201); } catch (error) { return fail(c, error); } });
routes.get('/:id', requirePermissions([PERMISSIONS.INTERVENTIONS_READ], 'PERMISSION_DENIED'), async (c) => { try { return c.json({ success: true, data: await Registry.getInstance().behaviouralInterventionOperationsUseCase.detail(String(c.req.param('id') ?? '')) }); } catch (error) { return fail(c, error); } });
for (const operation of ['submit','approve','activate','pause','complete'] as const) routes.post(`/:id/${operation}`, requirePermissions([operation === 'approve' ? PERMISSIONS.INTERVENTIONS_APPROVE : operation === 'activate' || operation === 'pause' ? PERMISSIONS.INTERVENTIONS_ACTIVATE : PERMISSIONS.INTERVENTIONS_MANAGE], 'PERMISSION_DENIED'), async (c) => { const body = operationBody.safeParse(await c.req.json().catch(() => null)); if (!body.success) return c.json({ success: false, error: { code: 'INVALID_BODY', message: body.error.issues[0]?.message ?? 'Invalid body.' } }, 400); try { const useCase = Registry.getInstance().behaviouralInterventionOperationsUseCase; const fn = useCase[operation].bind(useCase) as any; return c.json({ success: true, data: await fn({ id: c.req.param('id'), actorId: actor(c), ...body.data }) }); } catch (error) { return fail(c, error); } });
export default routes;
