import { createHash, randomUUID } from 'node:crypto';
import { and, asc, desc, eq, gte, inArray, sql } from 'drizzle-orm';
import { IBehaviouralInterventionRepository, InterventionDefinitionRecord, InterventionExposureRecord, InterventionVersionRecord } from '../../../application/ports/IBehaviouralInterventionRepository';
import { InterventionAudience, InterventionContent, InterventionOutcome, InterventionStatus, InterventionSuppression, TargetBehaviour, interventionParticipantHash } from '../../../domain/behavioural-interventions/BehaviouralIntervention';
import { deterministicVariant } from '../../../domain/experiments/Experiment';
import { client, db } from '../client';
import { consentCurrentState } from '../schema/consent';
import { customerProfiles } from '../schema/customer_dna';
import { experimentAssignments, experimentExposures, experiments, experimentVariants } from '../schema/experiments';
import { behaviouralInterventionDefinitions, behaviouralInterventionEvents, behaviouralInterventionExposures, behaviouralInterventionOutcomes, behaviouralInterventionVersions } from '../schema/behavioural_interventions';

const jsonb = (value: unknown) => sql`${client.json(value as any)}::jsonb`;
const definitionRecord = (row: typeof behaviouralInterventionDefinitions.$inferSelect): InterventionDefinitionRecord => ({ ...row, status: row.status as InterventionStatus });
const versionRecord = (row: typeof behaviouralInterventionVersions.$inferSelect): InterventionVersionRecord => ({ ...row, targetBehaviour: row.targetBehaviour as TargetBehaviour, channel: 'ON_SITE', audience: row.audience as InterventionAudience, content: row.content as InterventionContent, suppression: row.suppression as InterventionSuppression });
const exposureRecord = (row: typeof behaviouralInterventionExposures.$inferSelect): InterventionExposureRecord => ({ ...row, eligibilityEvidence: row.eligibilityEvidence as Record<string, unknown> });

export class DrizzleBehaviouralInterventionRepository implements IBehaviouralInterventionRepository {
  private event(tx: any, input: { definitionId: string; actorId: string; action: string; reason: string; evidence: Record<string, unknown> }) { return tx.insert(behaviouralInterventionEvents).values({ ...input, evidence: jsonb(input.evidence) as any }); }
  async findExperiment(id: string) { const [row] = await db.select({ id: experiments.id, status: experiments.status, hypothesis: experiments.hypothesis, primaryMetric: experiments.primaryMetric }).from(experiments).where(eq(experiments.id, id)).limit(1); if (!row) return null; const variants = await db.select({ key: experimentVariants.key, name: experimentVariants.name, weightBasisPoints: experimentVariants.weightBasisPoints }).from(experimentVariants).where(eq(experimentVariants.experimentId, id)).orderBy(asc(experimentVariants.createdAt)); return { ...row, variants }; }
  async create(input: { key: string; name: string; targetBehaviour: TargetBehaviour; hypothesis: string; primaryMetric: string; audience: InterventionAudience; channel: 'ON_SITE'; placement: string; content: InterventionContent; suppression: InterventionSuppression; experimentId: string; experimentVariantKey: string; contentDigest: string; actorId: string }) {
    return db.transaction(async (tx) => {
      const definitionId = randomUUID(); const versionId = randomUUID();
      const [definition] = await tx.insert(behaviouralInterventionDefinitions).values({ id: definitionId, key: input.key, currentVersionId: versionId, createdBy: input.actorId }).returning();
      await tx.insert(behaviouralInterventionVersions).values({ id: versionId, definitionId, versionNumber: 1, name: input.name, targetBehaviour: input.targetBehaviour, hypothesis: input.hypothesis, primaryMetric: input.primaryMetric, audience: jsonb(input.audience) as any, channel: input.channel, placement: input.placement, content: jsonb(input.content) as any, suppression: jsonb(input.suppression) as any, experimentId: input.experimentId, experimentVariantKey: input.experimentVariantKey, contentDigest: input.contentDigest, createdBy: input.actorId });
      await this.event(tx, { definitionId, actorId: input.actorId, action: 'CREATED', reason: 'Immutable ethical intervention version created.', evidence: { versionId, experimentId: input.experimentId, experimentVariantKey: input.experimentVariantKey, targetBehaviour: input.targetBehaviour, contentDigest: input.contentDigest } });
      return definitionRecord(definition);
    });
  }
  async list() {
    const rows = await db.select({ definition: behaviouralInterventionDefinitions, name: behaviouralInterventionVersions.name, exposures: sql<number>`count(distinct ${behaviouralInterventionExposures.id})::int`, outcomes: sql<number>`count(distinct ${behaviouralInterventionOutcomes.id})::int` }).from(behaviouralInterventionDefinitions).innerJoin(behaviouralInterventionVersions, eq(behaviouralInterventionVersions.id, behaviouralInterventionDefinitions.currentVersionId)).leftJoin(behaviouralInterventionExposures, eq(behaviouralInterventionExposures.definitionId, behaviouralInterventionDefinitions.id)).leftJoin(behaviouralInterventionOutcomes, eq(behaviouralInterventionOutcomes.definitionId, behaviouralInterventionDefinitions.id)).groupBy(behaviouralInterventionDefinitions.id, behaviouralInterventionVersions.name).orderBy(desc(behaviouralInterventionDefinitions.updatedAt));
    return rows.map((row) => ({ ...definitionRecord(row.definition), name: row.name, exposures: row.exposures, outcomes: row.outcomes }));
  }
  async detail(id: string) {
    const [row] = await db.select({ definition: behaviouralInterventionDefinitions, version: behaviouralInterventionVersions }).from(behaviouralInterventionDefinitions).innerJoin(behaviouralInterventionVersions, eq(behaviouralInterventionVersions.id, behaviouralInterventionDefinitions.currentVersionId)).where(eq(behaviouralInterventionDefinitions.id, id)).limit(1); if (!row) return null;
    const events = await db.select().from(behaviouralInterventionEvents).where(eq(behaviouralInterventionEvents.definitionId, id)).orderBy(asc(behaviouralInterventionEvents.createdAt));
    const outcomes = await db.select({ outcome: behaviouralInterventionOutcomes.outcome, count: sql<number>`count(*)::int` }).from(behaviouralInterventionOutcomes).where(eq(behaviouralInterventionOutcomes.definitionId, id)).groupBy(behaviouralInterventionOutcomes.outcome);
    const [exposureCount] = await db.select({ count: sql<number>`count(*)::int` }).from(behaviouralInterventionExposures).where(eq(behaviouralInterventionExposures.definitionId, id)); const count = (key: string) => outcomes.find((item) => item.outcome === key)?.count ?? 0;
    return { definition: definitionRecord(row.definition), version: versionRecord(row.version), events, measurement: { exposures: exposureCount?.count ?? 0, engaged: count('ENGAGED'), dismissed: count('DISMISSED'), targetAchieved: count('TARGET_ACHIEVED') } };
  }
  async transition(input: { id: string; expectedVersion: number; from: InterventionStatus[]; to: InterventionStatus; actorId: string; reason: string; requireDifferentActor?: boolean; requireRunningExperiment?: boolean }) {
    return db.transaction(async (tx) => {
      const conditions = [eq(behaviouralInterventionDefinitions.id, input.id), eq(behaviouralInterventionDefinitions.version, input.expectedVersion), inArray(behaviouralInterventionDefinitions.status, input.from)];
      if (input.requireDifferentActor) conditions.push(sql`${behaviouralInterventionDefinitions.createdBy} <> ${input.actorId}::uuid`);
      if (input.requireRunningExperiment) conditions.push(sql`exists (select 1 from behavioural_intervention_versions biv join experiments e on e.id=biv.experiment_id where biv.id=${behaviouralInterventionDefinitions.currentVersionId} and e.status='RUNNING')`);
      const [row] = await tx.update(behaviouralInterventionDefinitions).set({ status: input.to, approvedBy: input.to === 'APPROVED' ? input.actorId : undefined, version: sql`${behaviouralInterventionDefinitions.version} + 1`, updatedAt: new Date() }).where(and(...conditions)).returning(); if (!row) return null;
      await this.event(tx, { definitionId: input.id, actorId: input.actorId, action: input.to, reason: input.reason, evidence: { from: input.from, to: input.to, version: row.version } }); return definitionRecord(row);
    });
  }
  async eligible(userId: string) {
    const [profile] = await db.select().from(customerProfiles).where(and(eq(customerProfiles.accountUserId, userId), eq(customerProfiles.consentEligible, true))).limit(1);
    const [consent] = await db.select().from(consentCurrentState).where(and(eq(consentCurrentState.userId, userId), eq(consentCurrentState.personalizationGranted, true), sql`${consentCurrentState.expiresAt} is null or ${consentCurrentState.expiresAt} > now()`)).limit(1); if (!profile || !consent) return [];
    const rows = await db.select({ definition: behaviouralInterventionDefinitions, version: behaviouralInterventionVersions }).from(behaviouralInterventionDefinitions).innerJoin(behaviouralInterventionVersions, eq(behaviouralInterventionVersions.id, behaviouralInterventionDefinitions.currentVersionId)).innerJoin(experiments, eq(experiments.id, behaviouralInterventionVersions.experimentId)).where(and(eq(behaviouralInterventionDefinitions.status, 'ACTIVE'), eq(experiments.status, 'RUNNING')));
    const participantRefHash = interventionParticipantHash(userId); const eligible = [];
    for (const row of rows) { const version = versionRecord(row.version); if (version.audience.lifecycleStages.length && !version.audience.lifecycleStages.includes(profile.primaryLifecycleStage)) continue; const variants = await db.select({ key: experimentVariants.key, name: experimentVariants.name, weightBasisPoints: experimentVariants.weightBasisPoints }).from(experimentVariants).where(eq(experimentVariants.experimentId, version.experimentId)).orderBy(asc(experimentVariants.createdAt)); if (deterministicVariant(version.experimentId, participantRefHash, variants).key !== version.experimentVariantKey) continue; const since = new Date(Date.now() - version.suppression.windowHours * 3_600_000); const [count] = await db.select({ count: sql<number>`count(*)::int` }).from(behaviouralInterventionExposures).where(and(eq(behaviouralInterventionExposures.definitionId, row.definition.id), eq(behaviouralInterventionExposures.participantRefHash, participantRefHash), gte(behaviouralInterventionExposures.occurredAt, since))); const [dismissed] = version.suppression.suppressAfterDismissal ? await db.select({ id: behaviouralInterventionOutcomes.id }).from(behaviouralInterventionOutcomes).where(and(eq(behaviouralInterventionOutcomes.definitionId, row.definition.id), eq(behaviouralInterventionOutcomes.participantRefHash, participantRefHash), eq(behaviouralInterventionOutcomes.outcome, 'DISMISSED'))).limit(1) : [];
      if ((count?.count ?? 0) >= version.suppression.maxImpressions || dismissed) continue; eligible.push({ definition: definitionRecord(row.definition), version, eligibilityEvidence: { policy: 'behavioural-intervention-v1', consentRecordId: consent.lastConsentRecordId ?? consent.id, lifecycleStage: profile.primaryLifecycleStage, experimentId: version.experimentId, experimentVariantKey: version.experimentVariantKey, experimentStatus: 'RUNNING', impressionCount: count?.count ?? 0, checkedAt: new Date().toISOString() } }); }
    return eligible;
  }
  async expose(input: { definitionId: string; versionId: string; experimentId: string; userId: string; participantRefHash: string; deliveryKey: string; eligibilityEvidence: Record<string, unknown> }) {
    return db.transaction(async (tx) => {
      await tx.execute(sql`select pg_advisory_xact_lock(hashtext(${`${input.definitionId}:${input.participantRefHash}`}))`);
      const [existing] = await tx.select().from(behaviouralInterventionExposures).where(and(eq(behaviouralInterventionExposures.definitionId, input.definitionId), eq(behaviouralInterventionExposures.deliveryKey, input.deliveryKey))).limit(1); if (existing) return { exposure: exposureRecord(existing), duplicate: true };
      const [version] = await tx.select().from(behaviouralInterventionVersions).innerJoin(behaviouralInterventionDefinitions, eq(behaviouralInterventionDefinitions.currentVersionId, behaviouralInterventionVersions.id)).innerJoin(experiments, eq(experiments.id, behaviouralInterventionVersions.experimentId)).where(and(eq(behaviouralInterventionDefinitions.id, input.definitionId), eq(behaviouralInterventionDefinitions.status, 'ACTIVE'), eq(behaviouralInterventionVersions.id, input.versionId), eq(behaviouralInterventionVersions.experimentId, input.experimentId), eq(experiments.status, 'RUNNING'))).limit(1); if (!version) return null;
      const interventionVersion = version.behavioural_intervention_versions; const [profile] = await tx.select().from(customerProfiles).where(and(eq(customerProfiles.accountUserId, input.userId), eq(customerProfiles.consentEligible, true))).limit(1); const [consent] = await tx.select().from(consentCurrentState).where(and(eq(consentCurrentState.userId, input.userId), eq(consentCurrentState.personalizationGranted, true), sql`${consentCurrentState.expiresAt} is null or ${consentCurrentState.expiresAt} > now()`)).limit(1); const audience = interventionVersion.audience as InterventionAudience; if (!profile || !consent || (audience.lifecycleStages.length && !audience.lifecycleStages.includes(profile.primaryLifecycleStage))) return null; const suppression = interventionVersion.suppression as InterventionSuppression; const variants = await tx.select({ key: experimentVariants.key, name: experimentVariants.name, weightBasisPoints: experimentVariants.weightBasisPoints }).from(experimentVariants).where(eq(experimentVariants.experimentId, input.experimentId)).orderBy(asc(experimentVariants.createdAt)); const assignedVariant = deterministicVariant(input.experimentId, input.participantRefHash, variants); if (assignedVariant.key !== interventionVersion.experimentVariantKey) return null; const since = new Date(Date.now() - suppression.windowHours * 3_600_000);
      const [count] = await tx.select({ count: sql<number>`count(*)::int` }).from(behaviouralInterventionExposures).where(and(eq(behaviouralInterventionExposures.definitionId, input.definitionId), eq(behaviouralInterventionExposures.participantRefHash, input.participantRefHash), gte(behaviouralInterventionExposures.occurredAt, since))); const [dismissed] = suppression.suppressAfterDismissal ? await tx.select({ id: behaviouralInterventionOutcomes.id }).from(behaviouralInterventionOutcomes).where(and(eq(behaviouralInterventionOutcomes.definitionId, input.definitionId), eq(behaviouralInterventionOutcomes.participantRefHash, input.participantRefHash), eq(behaviouralInterventionOutcomes.outcome, 'DISMISSED'))).limit(1) : [];
      if ((count?.count ?? 0) >= suppression.maxImpressions || dismissed) return null;
      const insertedAssignment = await tx.insert(experimentAssignments).values({ experimentId: input.experimentId, subjectHash: input.participantRefHash, variantKey: assignedVariant.key }).onConflictDoNothing({ target: [experimentAssignments.experimentId, experimentAssignments.subjectHash] }).returning(); const assignment = insertedAssignment[0] ?? (await tx.select().from(experimentAssignments).where(and(eq(experimentAssignments.experimentId, input.experimentId), eq(experimentAssignments.subjectHash, input.participantRefHash))).limit(1))[0]; if (assignment.variantKey !== assignedVariant.key) return null; const experimentExposureKey = `behavioural:${createHash('sha256').update(`${input.definitionId}:${input.deliveryKey}`).digest('hex')}`; await tx.insert(experimentExposures).values({ assignmentId: assignment.id, experimentId: input.experimentId, exposureKey: experimentExposureKey, occurredAt: new Date() }).onConflictDoNothing({ target: [experimentExposures.experimentId, experimentExposures.exposureKey] }); const [created] = await tx.insert(behaviouralInterventionExposures).values({ definitionId: input.definitionId, versionId: input.versionId, experimentId: input.experimentId, participantRefHash: input.participantRefHash, deliveryKey: input.deliveryKey, eligibilityEvidence: jsonb({ ...input.eligibilityEvidence, consentRecordId: consent.lastConsentRecordId ?? consent.id, lifecycleStage: profile.primaryLifecycleStage, experimentVariantKey: assignedVariant.key, experimentExposureKey, checkedAt: new Date().toISOString() }) as any }).returning(); return { exposure: exposureRecord(created), duplicate: false };
    });
  }
  async findExposureByDelivery(definitionId: string, deliveryKey: string) { const [row] = await db.select().from(behaviouralInterventionExposures).where(and(eq(behaviouralInterventionExposures.definitionId, definitionId), eq(behaviouralInterventionExposures.deliveryKey, deliveryKey))).limit(1); return row ? exposureRecord(row) : null; }
  async findExposure(id: string) { const [row] = await db.select().from(behaviouralInterventionExposures).where(eq(behaviouralInterventionExposures.id, id)).limit(1); return row ? exposureRecord(row) : null; }
  async recordOutcome(input: { exposureId: string; definitionId: string; participantRefHash: string; outcomeKey: string; outcome: InterventionOutcome; source: 'CUSTOMER_ACTION' | 'SERVER_MEASUREMENT'; evidence: Record<string, unknown> }) { const inserted = await db.insert(behaviouralInterventionOutcomes).values({ ...input, evidence: jsonb(input.evidence) as any }).onConflictDoNothing({ target: [behaviouralInterventionOutcomes.definitionId, behaviouralInterventionOutcomes.outcomeKey] }).returning(); return { duplicate: inserted.length === 0 }; }
}
