export const PERMISSIONS = {
  AUTH_MANAGE: 'auth.manage',
  ROLES_MANAGE: 'roles.manage',
  PERMISSIONS_MANAGE: 'permissions.manage',
  AUDIT_READ: 'audit.read',
  AUDIT_EXPORT: 'audit.export',
  PRODUCTS_READ: 'products.read',
  PRODUCTS_WRITE: 'products.write',
  PRODUCTS_PUBLISH: 'products.publish',
  CATEGORIES_MANAGE: 'categories.manage',
  PRICING_MANAGE: 'pricing.manage',
  INVENTORY_READ: 'inventory.read',
  INVENTORY_ADJUST: 'inventory.adjust',
  ORDERS_READ: 'orders.read',
  ORDERS_MANAGE: 'orders.manage',
  PAYMENTS_READ: 'payments.read',
  PAYMENTS_CONFIRM: 'payments.confirm',
  DEALER_APPROVE: 'dealer.approve',
  DEALER_READ_PRIVATE: 'dealer.read_private',
  QUOTES_MANAGE: 'quotes.manage',
  LEADS_ASSIGN: 'leads.assign',
  CAMPAIGNS_MANAGE: 'campaigns.manage',
  CREATIVES_APPROVE: 'creatives.approve',
  FEEDS_PUBLISH: 'feeds.publish',
  ATTRIBUTION_READ: 'attribution.read',
  REPORTS_READ: 'reports.read',
  SETTINGS_MANAGE: 'settings.manage',
  NOTIFICATIONS_READ: 'notifications.read',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];
